// <auto-generated />
using System;
using AI.DocumentAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AI.DocumentAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616200332_AddOrganizationInvitationsNotificationsAndSettings")]
    partial class AddOrganizationInvitationsNotificationsAndSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.AiActionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultContentType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ResultFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResultFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "DocumentId", "CreatedAtUtc");

                    b.HasIndex("UserId", "TemplateId", "CreatedAtUtc");

                    b.ToTable("AiActionRuns", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.AiActionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SaveResult")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId", "FolderId");

                    b.HasIndex("UserId", "DocumentType", "Name");

                    b.ToTable("AiActionTemplates", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowSystemFolderCreation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AnalyzedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FirstOpenedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FolderClassificationConfidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("FolderClassificationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FolderClassificationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastProcessingAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizationMode")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessingAttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingProfile")
                        .HasColumnType("int");

                    b.Property<string>("QuickSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("SmartOrganizeRequested")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasFolderAutoAssigned")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId", "FolderId", "UploadedAtUtc");

                    b.HasIndex("UserId", "OrganizationMode", "UploadedAtUtc");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Embedding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.DocumentFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameUa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("UserId", "ParentFolderId", "Key")
                        .IsUnique()
                        .HasFilter("[ParentFolderId] IS NOT NULL");

                    b.ToTable("DocumentFolders", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.DocumentFolderSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExistingFolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ProposedKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProposedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProposedNameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProposedNamePl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProposedNameUa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ProposedParentFolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RuleScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("SemanticScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UserHistoryScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExistingFolderId");

                    b.HasIndex("ProposedParentFolderId");

                    b.HasIndex("DocumentId", "Rank");

                    b.HasIndex("UserId", "DocumentId", "Status");

                    b.ToTable("DocumentFolderSuggestions", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.DocumentIntelligenceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessDomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("UserId", "DocumentType", "BusinessDomain");

                    b.HasIndex("UserId", "Year", "Month");

                    b.ToTable("DocumentIntelligenceSnapshots", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.ExtractedData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtractionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JsonResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("ExtractedData", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.FolderEmbeddingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FolderId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("FolderEmbeddingProfiles", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name");

                    b.HasIndex("IsActive", "CreatedAtUtc");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.OrganizationActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OrganizationId", "CreatedAtUtc");

                    b.ToTable("OrganizationActivityLogs", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("InvitedUserId", "Status", "ExpiresAtUtc");

                    b.HasIndex("OrganizationId", "Email", "Status");

                    b.ToTable("OrganizationInvitations", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RemovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "IsActive");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("OrganizationMembers", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.OrganizationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvitationLifetimeDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("OrganizationSettings", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EmailConfirmationSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailConfirmationTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalProviderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasUnlimitedAiUsage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MonthlyChatMessageLimit")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyComparisonLimit")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyDocumentUploadLimit")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyExtractionLimit")
                        .HasColumnType("int");

                    b.Property<int>("MonthlySummarizationLimit")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("en");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.UserFolderRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CreatedFromCorrection")
                        .HasColumnType("bit");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastMatchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Topic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId", "FolderId", "Pattern");

                    b.ToTable("UserFolderRules", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DismissedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RelatedInvitationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedInvitationId");

                    b.HasIndex("RelatedOrganizationId");

                    b.HasIndex("UserId", "DismissedAtUtc", "ReadAtUtc", "CreatedAtUtc");

                    b.ToTable("UserNotifications", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.UserQuotaOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("HasUnlimitedAiUsageOverride")
                        .HasColumnType("bit");

                    b.Property<int?>("MonthlyChatMessageLimitOverride")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyComparisonLimitOverride")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyDocumentUploadLimitOverride")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyExtractionLimitOverride")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlySummarizationLimitOverride")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidToUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ValidFromUtc", "ValidToUtc");

                    b.ToTable("UserQuotaOverrides");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.UserUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsageType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAtUtc");

                    b.HasIndex("UserId", "UsageType", "OccurredAtUtc");

                    b.ToTable("UserUsageRecords");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.AiActionRun", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Document", "Document")
                        .WithMany("AiActionRuns")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.AiActionTemplate", "Template")
                        .WithMany("Runs")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("AiActionRuns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.AiActionTemplate", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.DocumentFolder", "Folder")
                        .WithMany("AiActionTemplates")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("AiActionTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Document", "Document")
                        .WithMany("ChatSessions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.DocumentFolder", "Folder")
                        .WithMany("ChatSessions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.Document", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.DocumentFolder", "Folder")
                        .WithMany("Documents")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.DocumentFolder", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.DocumentFolder", "ParentFolder")
                        .WithMany("Children")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("DocumentFolders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentFolder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.DocumentFolderSuggestion", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Document", "Document")
                        .WithMany("FolderSuggestions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.DocumentFolder", "ExistingFolder")
                        .WithMany("Suggestions")
                        .HasForeignKey("ExistingFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.DocumentFolder", "ProposedParentFolder")
                        .WithMany()
                        .HasForeignKey("ProposedParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("DocumentFolderSuggestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ExistingFolder");

                    b.Navigation("ProposedParentFolder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.DocumentIntelligenceSnapshot", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Document", "Document")
                        .WithOne("IntelligenceSnapshot")
                        .HasForeignKey("AI.DocumentAssistant.Domain.Entities.DocumentIntelligenceSnapshot", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("DocumentIntelligenceSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.ExtractedData", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Document", "Document")
                        .WithMany("Extractions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.FolderEmbeddingProfile", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.DocumentFolder", "Folder")
                        .WithOne("EmbeddingProfile")
                        .HasForeignKey("AI.DocumentAssistant.Domain.Entities.FolderEmbeddingProfile", "FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("FolderEmbeddingProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.Organization", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedOrganizations")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.OrganizationActivityLog", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "ActorUser")
                        .WithMany("OrganizationActivityLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Organization", "Organization")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.OrganizationInvitation", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "InvitedByUser")
                        .WithMany("SentOrganizationInvitations")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "InvitedUser")
                        .WithMany("ReceivedOrganizationInvitations")
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Organization", "Organization")
                        .WithMany("Invitations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "RevokedByUser")
                        .WithMany("RevokedOrganizationInvitations")
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");

                    b.Navigation("Organization");

                    b.Navigation("RevokedByUser");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.OrganizationMember", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "AddedByUser")
                        .WithMany("AddedOrganizationMembers")
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.OrganizationSettings", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Organization", "Organization")
                        .WithOne("Settings")
                        .HasForeignKey("AI.DocumentAssistant.Domain.Entities.OrganizationSettings", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.UserFolderRule", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.DocumentFolder", "Folder")
                        .WithMany("UserRules")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("FolderRules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.OrganizationInvitation", "RelatedInvitation")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedInvitationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.Organization", "RelatedOrganization")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedInvitation");

                    b.Navigation("RelatedOrganization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.UserQuotaOverride", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("QuotaOverrides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.UserUsageRecord", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Domain.Entities.User", "User")
                        .WithMany("UsageRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.AiActionTemplate", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.Document", b =>
                {
                    b.Navigation("AiActionRuns");

                    b.Navigation("ChatSessions");

                    b.Navigation("Chunks");

                    b.Navigation("Extractions");

                    b.Navigation("FolderSuggestions");

                    b.Navigation("IntelligenceSnapshot");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.DocumentFolder", b =>
                {
                    b.Navigation("AiActionTemplates");

                    b.Navigation("ChatSessions");

                    b.Navigation("Children");

                    b.Navigation("Documents");

                    b.Navigation("EmbeddingProfile");

                    b.Navigation("Suggestions");

                    b.Navigation("UserRules");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.Organization", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("Notifications");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.OrganizationInvitation", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Domain.Entities.User", b =>
                {
                    b.Navigation("AddedOrganizationMembers");

                    b.Navigation("AiActionRuns");

                    b.Navigation("AiActionTemplates");

                    b.Navigation("CreatedOrganizations");

                    b.Navigation("DocumentFolderSuggestions");

                    b.Navigation("DocumentFolders");

                    b.Navigation("DocumentIntelligenceSnapshots");

                    b.Navigation("Documents");

                    b.Navigation("FolderEmbeddingProfiles");

                    b.Navigation("FolderRules");

                    b.Navigation("Notifications");

                    b.Navigation("OrganizationActivityLogs");

                    b.Navigation("OrganizationMemberships");

                    b.Navigation("QuotaOverrides");

                    b.Navigation("ReceivedOrganizationInvitations");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RevokedOrganizationInvitations");

                    b.Navigation("SentOrganizationInvitations");

                    b.Navigation("UsageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
