using System.Text;
using System.Text.RegularExpressions;
using AI.DocumentAssistant.Application.Abstractions.Documents;
using SkiaSharp;

namespace AI.DocumentAssistant.Application.Documents.Services;

public sealed class SimpleAiActionPdfRenderer : IAiActionPdfRenderer
{
    private const float PageWidth = 595f;
    private const float PageHeight = 842f;
    private const float Margin = 48f;
    private const float HeaderY = 58f;
    private const float BodyTop = 112f;
    private const float BodyBottom = 780f;
    private const float FooterY = 812f;

    private static readonly Lazy<PdfFontSet> Fonts = new(LoadFonts);

    public byte[] RenderTextReport(string title, string content, string? language)
    {
        var safeTitle = CleanInlineMarkdown(string.IsNullOrWhiteSpace(title) ? "AI Action Report" : title.Trim());
        var safeContent = NormalizeText(string.IsNullOrWhiteSpace(content) ? "No content was generated." : content.Trim());
        var fontSet = Fonts.Value;

        using var output = new MemoryStream();
        using var document = SKDocument.CreatePdf(output, new SKDocumentPdfMetadata
        {
            Title = safeTitle,
            Author = "AI Document Assistant",
            Creator = "AI Document Assistant",
            Subject = "AI action result",
            Creation = DateTime.UtcNow,
            Modified = DateTime.UtcNow
        });

        using var titlePaint = CreatePaint(fontSet.Bold, 17f, SKColors.Black);
        using var metaPaint = CreatePaint(fontSet.Regular, 8.5f, new SKColor(110, 110, 110));
        using var bodyPaint = CreatePaint(fontSet.Regular, 10.2f, SKColors.Black);
        using var headingPaint = CreatePaint(fontSet.Bold, 12.5f, SKColors.Black);
        using var footerPaint = CreatePaint(fontSet.Regular, 8.5f, new SKColor(120, 120, 120));
        using var linePaint = new SKPaint { Color = new SKColor(210, 210, 210), StrokeWidth = 1, IsAntialias = true };

        var lines = BuildLayoutLines(safeContent, bodyPaint, headingPaint, PageWidth - Margin * 2);
        if (lines.Count == 0)
        {
            lines.Add(new PdfLine("No content was generated.", bodyPaint, 14.2f, false));
        }

        var pageNumber = 1;
        var canvas = BeginPage(document, safeTitle, language, pageNumber, titlePaint, metaPaint, linePaint);
        var y = BodyTop;

        foreach (var line in lines)
        {
            if (y + line.Height > BodyBottom)
            {
                DrawFooter(canvas, footerPaint, linePaint, pageNumber);
                document.EndPage();
                pageNumber++;
                canvas = BeginPage(document, safeTitle, language, pageNumber, titlePaint, metaPaint, linePaint);
                y = BodyTop;
            }

            if (!string.IsNullOrWhiteSpace(line.Text))
            {
                var x = Margin + (line.Indented ? 14f : 0f);
                DrawTextLine(canvas, line.Text, x, y, line.Paint);
            }

            y += line.Height;
        }

        DrawFooter(canvas, footerPaint, linePaint, pageNumber);
        document.EndPage();
        document.Close();

        return output.ToArray();
    }

    private static SKCanvas BeginPage(
        SKDocument document,
        string title,
        string? language,
        int pageNumber,
        SKPaint titlePaint,
        SKPaint metaPaint,
        SKPaint linePaint)
    {
        var canvas = document.BeginPage(PageWidth, PageHeight);
        canvas.Clear(SKColors.White);

        DrawTextLine(canvas, title, Margin, HeaderY, titlePaint);
        var label = NormalizeLanguage(language) switch
        {
            "pl" => $"Wygenerowano przez AI Document Assistant - strona {pageNumber}",
            "ua" => $"Створено AI Document Assistant - сторінка {pageNumber}",
            _ => $"Generated by AI Document Assistant - page {pageNumber}"
        };

        DrawTextLine(canvas, label, Margin, HeaderY + 24f, metaPaint);
        canvas.DrawLine(Margin, HeaderY + 44f, PageWidth - Margin, HeaderY + 44f, linePaint);
        return canvas;
    }

    private static void DrawFooter(SKCanvas canvas, SKPaint footerPaint, SKPaint linePaint, int pageNumber)
    {
        canvas.DrawLine(Margin, FooterY - 14f, PageWidth - Margin, FooterY - 14f, linePaint);
        DrawTextLine(canvas, $"AI Document Assistant - {DateTime.Now:g} - page {pageNumber}", Margin, FooterY, footerPaint);
    }

    private static SKPaint CreatePaint(SKTypeface typeface, float size, SKColor color)
        => new()
        {
            Typeface = typeface,
            TextSize = size,
            Color = color,
            IsAntialias = true,
            SubpixelText = true,
            LcdRenderText = true,
            HintingLevel = SKPaintHinting.Normal
        };

    private static void DrawTextLine(SKCanvas canvas, string text, float x, float topY, SKPaint paint)
    {
        var metrics = paint.FontMetrics;
        var baseline = topY - metrics.Ascent;
        canvas.DrawText(text, x, baseline, paint);
    }

    private static List<PdfLine> BuildLayoutLines(
        string content,
        SKPaint bodyPaint,
        SKPaint headingPaint,
        float maxWidth)
    {
        var result = new List<PdfLine>();
        var normalized = content.Replace("\r\n", "\n").Replace('\r', '\n');

        foreach (var rawParagraph in normalized.Split('\n'))
        {
            var paragraph = rawParagraph.TrimEnd();
            if (string.IsNullOrWhiteSpace(paragraph))
            {
                result.Add(new PdfLine(string.Empty, bodyPaint, 9f, false));
                continue;
            }

            var trimmed = paragraph.TrimStart();
            var isHeading = trimmed.StartsWith("#", StringComparison.Ordinal);
            var isBullet = trimmed.StartsWith("- ", StringComparison.Ordinal) ||
                           trimmed.StartsWith("* ", StringComparison.Ordinal) ||
                           trimmed.StartsWith("• ", StringComparison.Ordinal) ||
                           Regex.IsMatch(trimmed, @"^\d+[\.)]\s+");

            if (isHeading)
            {
                var heading = CleanInlineMarkdown(trimmed.TrimStart('#', ' ').Trim());
                if (!string.IsNullOrWhiteSpace(heading))
                {
                    foreach (var wrapped in WrapByMeasuredWidth(heading, headingPaint, maxWidth))
                    {
                        result.Add(new PdfLine(wrapped, headingPaint, 19f, false));
                    }
                }
                continue;
            }

            var text = CleanInlineMarkdown(trimmed);
            var indented = false;
            if (isBullet)
            {
                text = NormalizeBullet(text);
                indented = true;
            }

            foreach (var wrapped in WrapByMeasuredWidth(text, bodyPaint, maxWidth - (indented ? 14f : 0f)))
            {
                result.Add(new PdfLine(wrapped, bodyPaint, 14.2f, indented));
            }
        }

        TrimTrailingBlankLines(result);
        return result;
    }

    private static string NormalizeBullet(string value)
    {
        var trimmed = value.TrimStart();
        if (trimmed.StartsWith("• ", StringComparison.Ordinal))
        {
            return "- " + trimmed[2..].TrimStart();
        }

        if (trimmed.StartsWith("- ", StringComparison.Ordinal) || trimmed.StartsWith("* ", StringComparison.Ordinal))
        {
            return "- " + trimmed[2..].TrimStart();
        }

        var numbered = Regex.Match(trimmed, @"^\d+[\.)]\s+(.*)$");
        return numbered.Success ? "- " + numbered.Groups[1].Value.TrimStart() : "- " + trimmed;
    }

    private static IEnumerable<string> WrapByMeasuredWidth(string value, SKPaint paint, float maxWidth)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            yield return string.Empty;
            yield break;
        }

        var words = value.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var current = new StringBuilder();

        foreach (var word in words)
        {
            var candidate = current.Length == 0 ? word : current + " " + word;
            if (paint.MeasureText(candidate) <= maxWidth)
            {
                current.Clear();
                current.Append(candidate);
                continue;
            }

            if (current.Length > 0)
            {
                yield return current.ToString();
                current.Clear();
            }

            if (paint.MeasureText(word) <= maxWidth)
            {
                current.Append(word);
                continue;
            }

            foreach (var chunk in SplitLongWord(word, paint, maxWidth))
            {
                yield return chunk;
            }
        }

        if (current.Length > 0)
        {
            yield return current.ToString();
        }
    }

    private static IEnumerable<string> SplitLongWord(string word, SKPaint paint, float maxWidth)
    {
        var current = new StringBuilder();
        foreach (var ch in word)
        {
            var candidate = current.ToString() + ch;
            if (current.Length > 0 && paint.MeasureText(candidate) > maxWidth)
            {
                yield return current.ToString();
                current.Clear();
            }
            current.Append(ch);
        }

        if (current.Length > 0)
        {
            yield return current.ToString();
        }
    }

    private static void TrimTrailingBlankLines(List<PdfLine> lines)
    {
        while (lines.Count > 0 && string.IsNullOrWhiteSpace(lines[^1].Text))
        {
            lines.RemoveAt(lines.Count - 1);
        }
    }

    private static string CleanInlineMarkdown(string value)
        => value
            .Replace("**", string.Empty)
            .Replace("__", string.Empty)
            .Replace("`", string.Empty)
            .Trim();

    private static string NormalizeText(string value)
        => value
            .Replace('\u0000', ' ')
            .Replace("\t", "    ")
            .Replace('–', '-')
            .Replace('—', '-')
            .Replace('“', '"')
            .Replace('”', '"')
            .Replace('’', '\'')
            .Replace("…", "...");

    private static string NormalizeLanguage(string? language)
    {
        if (string.IsNullOrWhiteSpace(language)) return "en";
        var normalized = language.Trim().ToLowerInvariant();
        if (normalized.StartsWith("pl", StringComparison.Ordinal)) return "pl";
        if (normalized.StartsWith("ua", StringComparison.Ordinal) || normalized.StartsWith("uk", StringComparison.Ordinal)) return "ua";
        return "en";
    }

    private static PdfFontSet LoadFonts()
    {
        var regularPath = ResolveFontPath(bold: false);
        var boldPath = ResolveFontPath(bold: true);

        var regular = SKTypeface.FromFile(regularPath) ?? throw new InvalidOperationException($"Could not load PDF font: {regularPath}");
        var bold = SKTypeface.FromFile(boldPath) ?? regular;

        return new PdfFontSet(regular, bold);
    }

    private static string ResolveFontPath(bool bold)
    {
        var env = Environment.GetEnvironmentVariable(bold
            ? "AI_DOCUMENT_ASSISTANT_PDF_FONT_BOLD"
            : "AI_DOCUMENT_ASSISTANT_PDF_FONT_REGULAR");

        var candidates = new List<string>();
        if (!string.IsNullOrWhiteSpace(env))
        {
            candidates.Add(env);
        }

        candidates.AddRange(bold ? BoldCandidates() : RegularCandidates());

        var match = candidates.FirstOrDefault(File.Exists);
        if (match is not null)
        {
            return match;
        }

        throw new InvalidOperationException(
            "No Unicode TrueType font was found for PDF generation. " +
            "Install DejaVu Sans, Noto Sans, Arial, Segoe UI, Liberation Sans, or set " +
            "AI_DOCUMENT_ASSISTANT_PDF_FONT_REGULAR and AI_DOCUMENT_ASSISTANT_PDF_FONT_BOLD to .ttf files.");
    }

    private static IEnumerable<string> RegularCandidates()
    {
        yield return @"C:\Windows\Fonts\arial.ttf";
        yield return @"C:\Windows\Fonts\segoeui.ttf";
        yield return @"C:\Windows\Fonts\tahoma.ttf";
        yield return @"C:\Windows\Fonts\verdana.ttf";
        yield return @"C:\Windows\Fonts\calibri.ttf";
        yield return "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf";
        yield return "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf";
        yield return "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf";
        yield return "/usr/share/fonts/truetype/freefont/FreeSans.ttf";
        yield return "/System/Library/Fonts/Supplemental/Arial.ttf";
        yield return "/System/Library/Fonts/Supplemental/Arial Unicode.ttf";
    }

    private static IEnumerable<string> BoldCandidates()
    {
        yield return @"C:\Windows\Fonts\arialbd.ttf";
        yield return @"C:\Windows\Fonts\segoeuib.ttf";
        yield return @"C:\Windows\Fonts\tahomabd.ttf";
        yield return @"C:\Windows\Fonts\verdanab.ttf";
        yield return @"C:\Windows\Fonts\calibrib.ttf";
        yield return "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf";
        yield return "/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf";
        yield return "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf";
        yield return "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf";
        yield return "/System/Library/Fonts/Supplemental/Arial Bold.ttf";
    }

    private sealed record PdfLine(string Text, SKPaint Paint, float Height, bool Indented);
    private sealed record PdfFontSet(SKTypeface Regular, SKTypeface Bold);
}
